services:
  - type: web
    name: tla-annotation-app
    runtime: python
    repo: https://github.com/the-learning-agency-lab/annotation-app
    plan: starter
    branch: main
    buildCommand: ./setup.sh
    startCommand: prodigy adjudicate ume-adjudicate inputs/ume/ -F recipes/universal-math-exam-adjudication/adjudicate.py -dp recipes/universal-math-exam-adjudication/mcq.jinja2
    envVars:
      - key: PRODIGY_KEY
        sync: false      
      - key: PRODIGY_ALLOWED_SESSIONS
        sync: false
      - key: PRODIGY_CONFIG
        value: prodigy-production.json
      - key: PGDATABASE
        fromDatabase:
          name: prodigyDB
          property: database
      - key: PGHOST
        fromDatabase:
          name: prodigyDB
          property: host
      - key: PGUSER
        fromDatabase:
          name: prodigyDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: prodigyDB
          property: password
databases:
  - name: prodigyDB
    databaseName: prodigy
    plan: basic-256mb
